name: My-First-Workflow

on: 
  push:
    branches: 
        - main
  workflow_dispatch:

jobs: 
  My-First-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting the World
        run: echo "Hello World ðŸ‘‹"
      
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: List the files in repository
        run: |
          echo "The repository {{github.repository}} contains the following files:"
          tree
        
    
